# Generated by Django 2.1.4 on 2020-09-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlseo',
            name='match_type',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('prefix', 'Prefix')], default='exact', max_length=40, verbose_name='Open graph type'),
        ),
        migrations.AlterField(
            model_name='modelinstanceseo',
            name='content_type',
            field=models.ForeignKey(help_text='Please select the type (model) for the relation, you want to build.', limit_choices_to={'app_label__in': ['article', 'auth'], 'model__in': ['article', 'user']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type'),
        ),
    ]
